services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    networks:
      - neo4j_net

  neo4j-test:
    image: neo4j:latest
    volumes:
      - /$HOME/neo4j-test/logs:/logs
      - /$HOME/neo4j-test/config:/config
      - /$HOME/neo4j-test/data:/data
      - /$HOME/neo4j-test/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test_password
    ports:
      - "8474:7474"
      - "8687:7687"
    restart: always
    networks:
      - neo4j_net


networks:
  neo4j_net:
    driver: bridge